spring.application.name=bd

spring.datasource.url=\jdbc:postgresql://localhost:5433/produtosdb
spring.datasource.username=postgres
spring.datasouce.password=db_pp1
spring.datasource.driver-class-name=\
  org.postgresql.Driver